# port
server:
  port: 80

# Multipart, My-SQL, JPA Setting, Thymeleaf
spring:
  servlet:
    multipart:
      location: C:/gangnampro2/image/upload
      max-file-size: 10MB
      max-request-size: 10MB
  thymeleaf:
    cache: false                    # .html 변경사항 실시간 반영 (운영시는 true)
    check-template-location: true   # .templates 디렉토리에 파일이 있는지 없는지 체크, 없으면 에러를 발생
    prefix: classpath:templates/    # .html 파일을 불러오기 위한 경로 설정(src/main/resources/templates)
    suffix: .html                   # .return 뒤에붙는 html 생략가능
  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://mydb.cduwswms8soj.ap-northeast-2.rds.amazonaws.com:3306/gangnam_project2?autoReconnect=true&useUnicode=true&characterEncoding=utf-8
      username: project2
      password: project2
  jpa:
    hibernate:
      ddl-auto: none
    generate:
      ddl: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true

# Hibernate SQL 로그 출력
logging:
  level:
    org.hibernate.SQL: debug
